version: 2
updates:
  - package-ecosystem: npm
    directory: /ui-engine
    schedule: {interval: weekly}
    groups:
      minor-and-patch: {update-types: [minor, patch]}
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: /dstns-operator-cli
    schedule: {interval: weekly}
    open-pull-requests-limit: 3
  - package-ecosystem: pip
    directory: /docs
    schedule: {interval: monthly}
  - package-ecosystem: github-actions
    directory: /
    schedule: {interval: monthly}
  - package-ecosystem: docker
    directory: /
    schedule: {interval: monthly}
  - package-ecosystem: docker
    directory: /docker/gateway
    schedule: {interval: monthly}
