# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Varun Karthic

# Embed compiled SPIR-V into a C++ source file, with the hashes that identify
# it. Run with cmake -P; arguments are |-separated lists:
#   NAMES       shader names, in name order
#   SPIRV       the matching .spv files
#   SOURCE_DIR  repository root, to hash each shader's GLSL and its includes
#   COMPILER    the compiler that produced the SPIR-V, or "precompiled"
#   OUTPUT      the .cpp to write (rewritten only when its content changes)

string(REPLACE "|" ";" names "${NAMES}")
string(REPLACE "|" ";" files "${SPIRV}")
list(LENGTH names count)
math(EXPR last "${count} - 1")
file(READ "${SOURCE_DIR}/shaders/include/dstns_physics.h" physics)
file(READ "${SOURCE_DIR}/shaders/include/dstns_glsl.h" prelude)
file(READ "${SOURCE_DIR}/shaders/include/dstns_fields.h" fields)
file(READ "${SOURCE_DIR}/shaders/include/dstns_hydrology.h" hydrology)
file(READ "${SOURCE_DIR}/shaders/include/dstns_hydro_bindings.h" hydro_bindings)

set(arrays "")
set(entries "")
set(hashes "")
foreach(i RANGE ${last})
  list(GET names ${i} name)
  list(GET files ${i} spirv)
  file(READ "${spirv}" hex HEX)
  string(LENGTH "${hex}" length)
  math(EXPR remainder "${length} % 8")
  if(NOT remainder EQUAL 0 OR length EQUAL 0)
    message(FATAL_ERROR "${spirv} is not a SPIR-V module")
  endif()
  math(EXPR words "${length} / 8")
  # SPIR-V words are little-endian.
  string(REGEX REPLACE "([0-9a-f][0-9a-f])([0-9a-f][0-9a-f])([0-9a-f][0-9a-f])([0-9a-f][0-9a-f])" "0x\\4\\3\\2\\1u," body "${hex}")
  file(SHA256 "${spirv}" spirv_hash)
  file(READ "${SOURCE_DIR}/shaders/${name}.comp" source)
  string(SHA256 source_hash "${source}${prelude}${physics}${fields}${hydrology}${hydro_bindings}")
  string(APPEND arrays "const std::uint32_t k_${name}[] = {${body}};\n")
  string(APPEND entries "    {\"${name}\", k_${name}, ${words}, \"${spirv_hash}\", \"${source_hash}\"},\n")
  string(APPEND hashes "${spirv_hash}")
endforeach()
string(SHA256 bundle "${hashes}")

set(content "// Generated by cmake/EmbedSpirv.cmake. Do not edit.\n\n#include \"shaders.hpp\"\n\n#include <cstring>\n\nnamespace dstns::vulkan::shaders {\nnamespace {\n${arrays}} // namespace\n\nconst Binary kShaders[] = {\n${entries}};\nconst std::size_t kShaderCount = ${count};\nconst char* const kBundleSha256 = \"${bundle}\";\nconst char* const kCompiler = \"${COMPILER}\";\n\nconst Binary* find(const char* name) {\n    for (std::size_t i = 0; i < kShaderCount; ++i)\n        if (std::strcmp(kShaders[i].name, name) == 0) return &kShaders[i];\n    return nullptr;\n}\n\n} // namespace dstns::vulkan::shaders\n")
if(EXISTS "${OUTPUT}")
  file(READ "${OUTPUT}" previous)
  if(previous STREQUAL content)
    return()
  endif()
endif()
file(WRITE "${OUTPUT}" "${content}")
