# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Varun Karthic

# Copy freshly compiled SPIR-V into shaders/spirv/ and record the source each
# module was compiled from, so builds without a shader compiler can use it and
# can tell when it is out of date. Run by the dstns_refresh_spirv target.

string(REPLACE "|" ";" names "${NAMES}")
file(READ "${SOURCE_DIR}/shaders/include/dstns_physics.h" physics)
file(READ "${SOURCE_DIR}/shaders/include/dstns_glsl.h" prelude)
set(manifest "# Generated by the dstns_refresh_spirv target: shader, SHA-256 of its GLSL sources.\n# Compiler: ${COMPILER}\n")
foreach(name IN LISTS names)
  file(COPY_FILE "${BINARY_DIR}/shaders/${name}.spv" "${SOURCE_DIR}/shaders/spirv/${name}.spv")
  file(READ "${SOURCE_DIR}/shaders/${name}.comp" source)
  string(SHA256 source_hash "${source}${prelude}${physics}")
  string(APPEND manifest "${name} ${source_hash}\n")
endforeach()
file(WRITE "${SOURCE_DIR}/shaders/spirv/manifest.txt" "${manifest}")
message(STATUS "Committed SPIR-V refreshed in shaders/spirv/")
